In [13]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt 
%matplotlib inline 
import seaborn as sns
import datetime
from datetime import date, timedelta

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib
from scipy.stats import norm
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix

import pylab as pl
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

import pickle

from sklearn.tree import DecisionTreeClassifier

from sklearn.tree import export_graphviz 
    #In the cmd line type: conda install python-graphviz
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'D:/Program Files (x86)/Graphviz2.38/bin/'

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_curve
from sklearn.ensemble import RandomForestClassifier

# בניית דאטה ב
 חיתוך את כל מי שיש לו בדלתא תאריכים-פחות מ1 =אנשים שקבעו פגישה באותו יום או אחרי המועד שהתקיימה

3 הורדת שדות מיותרים נשארנו עם : 'AppointmentDay', 'Scholarship', 'Hipertension', 'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show', 'ScheduledWeekDay', 'prcp', 'temp', 'Gender_', 'No-show_', 'Delta_Dates', 'Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday', 'Appointment_counts', 'ADOULT', 'KID', 'OLD', 'YOUNG' 4 שמירת הדאטה

In [14]:
df = pd.read_csv("no_show_original_data_2016.csv")

In [15]:
#ScheduledDay קיצוץ התאריך של והופך את התאריך לסוג דייטיים
df['ScheduledDay'] =df['ScheduledDay'].apply(str)
df['ScheduledDay'] = df['ScheduledDay'].str.slice(0, 10, 1) 
df['ScheduledDay'] =  pd.to_datetime(df['ScheduledDay'], format='%Y-%m-%d')

In [16]:
#AppointmentDay הופך את התאריך לסוג דייטיים
df['AppointmentDay'] =df['AppointmentDay'].apply(str)
df['AppointmentDay'] = df['AppointmentDay'].str.slice(0, 10, 1) 
df['AppointmentDay'] =  pd.to_datetime(df['AppointmentDay'], format='%Y-%m-%d')

In [17]:
# הכנסת קודים לשכונות
df.loc[:, 'Neighbourhood_codes'] = df["Neighbourhood"].astype("category").cat.codes+1
# הפיכת שדות קטגוריים לבינריים
df.loc[:, 'Gender_'] = df["Gender"].astype("category").cat.codes
#Woman=0, Man=1
df.loc[:, 'No-show_'] = df["No-show"].astype("category").cat.codes
#show=0, no-show=1

In [18]:
#הוספת שדה של יום בשבוע של הבדיקה
dayOfWeek={0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday', 4:'Friday', 5:'Saturday', 6:'Sunday'}
df['Appointment_Week_Day'] = df['AppointmentDay'].dt.dayofweek.map(dayOfWeek)

In [19]:
#הוספת שדה של המרווח בין הבדיקות
df['Delta_Dates'] = (df['AppointmentDay']-df['ScheduledDay']).dt.days
# בדיקות שתואמו אחרי הבדיקה עצמה יופיעו כמינוס 1-כי לא הגיוני
mask = df.Delta_Dates < 0
column_name = 'Delta_Dates'
df.loc[mask, column_name] = -1

In [20]:
# חיתוך כל מי שיש לו דלתא קטנה מ1
df = df.drop(df[df.Delta_Dates < 1].index)

In [21]:
#Get Dummies לימי השבוע של הפגישה
week_day=pd.get_dummies(df["Appointment_Week_Day"])
week_day["AppointmentID"] = df["AppointmentID"]
df=df.merge(week_day, how='left', on='AppointmentID')
df = df.drop(['Appointment_Week_Day'], axis=1)

In [22]:
# מוסיף עמודה של כמות פגישות לכל מטופל
a=df.groupby(['PatientId']).size().reset_index(name='Appointment_counts')
df=df.merge(a, how='left', on='PatientId')
#בדיקה עצמית לקוד
#df.loc[df['PatientId'] == 1.885170e+14]

In [23]:
#Get Dummies לשכונות
NC=pd.get_dummies(df["Neighbourhood_codes"])
NC["AppointmentID"] = df["AppointmentID"]
df=df.merge(NC, how='left', on='AppointmentID')

In [25]:
# הוספת עמודת התאריך של אתמול
df["yesterday"] = df["AppointmentDay"] - timedelta(1)

In [28]:
# הוספת עמודה שסוכמת את כל ההברזות אתמול
#צריך למצוא פיתרון ליום שני?
df = df.sort_values(by='AppointmentDay')
count_y_total_meetings = 
df
#df["y_no_show_p"]

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,...,73,74,75,76,77,78,79,80,81,yesterday
0,2.366230e+14,5628286,M,2016-04-27,2016-04-29,0,SÃO BENEDITO,0,0,0,...,0,0,1,0,0,0,0,0,0,2016-04-28
52751,7.544920e+13,5625104,F,2016-04-27,2016-04-29,56,CENTRO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52750,1.484140e+12,5573128,F,2016-04-12,2016-04-29,56,GRANDE VITÓRIA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52749,9.977160e+14,5451635,F,2016-03-10,2016-04-29,56,GURIGICA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52748,7.537280e+13,5636838,F,2016-04-28,2016-04-29,56,ILHA DO PRÍNCIPE,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52747,2.349970e+11,5413185,F,2016-03-01,2016-04-29,56,DO CABRAL,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52746,4.727620e+13,5601894,M,2016-04-19,2016-04-29,56,SÃO JOSÉ,0,0,0,...,0,0,0,0,1,0,0,0,0,2016-04-28
52745,7.116340e+14,5502125,F,2016-03-22,2016-04-29,56,RESISTÊNCIA,0,1,1,...,0,0,0,0,0,0,0,0,0,2016-04-28
52744,8.361420e+13,5611825,F,2016-04-25,2016-04-29,56,JUCUTUQUARA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52743,7.123990e+13,5631867,M,2016-04-28,2016-04-29,56,PRAIA DO CANTO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52742,1.482630e+13,5600587,F,2016-04-19,2016-04-29,56,GRANDE VITÓRIA,0,0,1,...,0,0,0,0,0,0,0,0,0,2016-04-28
52741,2.178300e+13,5531300,F,2016-03-31,2016-04-29,56,JOANA D´ARC,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52740,6.787690e+11,5563183,M,2016-04-08,2016-04-29,56,JARDIM DA PENHA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52739,1.918230e+12,5625001,F,2016-04-26,2016-04-29,56,VILA RUBIM,0,1,1,...,0,0,0,0,0,0,0,0,1,2016-04-28
52738,2.667290e+12,5592387,M,2016-04-18,2016-04-29,56,CENTRO,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52737,6.771830e+14,5629128,F,2016-04-27,2016-04-29,56,COMDUSA,0,1,1,...,0,0,0,0,0,0,0,0,0,2016-04-28
52736,7.113870e+13,5634080,M,2016-04-28,2016-04-29,56,CENTRO,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52735,5.412290e+13,5510409,F,2016-03-23,2016-04-29,56,SOLON BORGES,0,0,0,...,0,1,0,0,0,0,0,0,0,2016-04-28
52734,5.142790e+13,5493693,F,2016-03-21,2016-04-29,56,SÃO CRISTÓVÃO,0,1,0,...,0,0,0,1,0,0,0,0,0,2016-04-28
52733,9.873740e+12,5631146,F,2016-04-27,2016-04-29,56,MARUÍPE,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52732,1.726360e+11,5631239,F,2016-04-27,2016-04-29,56,TABUAZEIRO,0,0,1,...,0,0,0,0,0,0,1,0,0,2016-04-28
52731,3.772420e+11,5574534,F,2016-04-12,2016-04-29,56,SANTO ANTÔNIO,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
9184,8.211530e+12,5624107,M,2016-04-26,2016-04-29,9,CARATOÍRA,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
9185,8.783880e+13,5568957,M,2016-04-11,2016-04-29,9,NOVA PALESTINA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
9186,6.179540e+12,5472950,F,2016-03-15,2016-04-29,9,NOVA PALESTINA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
9187,9.439380e+13,5603805,M,2016-04-20,2016-04-29,9,SÃO PEDRO,1,0,0,...,0,0,0,0,0,1,0,0,0,2016-04-28
9188,5.984220e+14,5565582,F,2016-04-11,2016-04-29,9,CENTRO,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
9189,2.921470e+13,5592287,F,2016-04-18,2016-04-29,9,PARQUE MOSCOSO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
52752,4.967770e+11,5628714,F,2016-04-27,2016-04-29,56,SÃO JOSÉ,0,0,0,...,0,0,0,0,1,0,0,0,0,2016-04-28
9190,2.499580e+14,5530673,F,2016-03-31,2016-04-29,9,SANTO ANTÔNIO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-04-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42214,3.979810e+12,5773648,F,2016-06-06,2016-06-08,45,JESUS DE NAZARETH,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
32713,1.975840e+11,5726019,F,2016-05-20,2016-06-08,35,BELA VISTA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
32640,6.123160e+13,5774409,M,2016-06-06,2016-06-08,35,SÃO CRISTÓVÃO,0,0,0,...,0,0,0,1,0,0,0,0,0,2016-06-07
3861,8.246300e+12,5649066,M,2016-05-02,2016-06-08,2,MARIA ORTIZ,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42170,3.464390e+14,5778267,M,2016-06-06,2016-06-08,45,ITARARÉ,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
69426,6.932190e+14,5766802,F,2016-06-02,2016-06-08,78,ILHA DO PRÍNCIPE,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
7327,9.818930e+12,5701275,F,2016-05-16,2016-06-08,6,SANTA TEREZA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42134,6.592780e+13,5685873,F,2016-05-11,2016-06-08,45,JABOUR,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42135,3.848320e+13,5693576,F,2016-05-13,2016-06-08,45,SEGURANÇA DO LAR,0,0,0,...,1,0,0,0,0,0,0,0,0,2016-06-07
42140,7.791780e+11,5779087,F,2016-06-06,2016-06-08,45,DA PENHA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42141,1.257310e+11,5654945,F,2016-05-03,2016-06-08,45,SANTA TEREZA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
18794,1.191520e+12,5778603,M,2016-06-06,2016-06-08,20,SÃO CRISTÓVÃO,1,0,0,...,0,0,0,1,0,0,0,0,0,2016-06-07
42146,2.794540e+14,5778491,F,2016-06-06,2016-06-08,45,JESUS DE NAZARETH,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42147,6.229160e+12,5768546,F,2016-06-03,2016-06-08,45,RESISTÊNCIA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
7319,1.252950e+14,5684773,F,2016-05-11,2016-06-08,6,JESUS DE NAZARETH,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42160,1.192900e+14,5775944,F,2016-06-06,2016-06-08,45,SANTO ANTÔNIO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
7318,7.492740e+13,5715860,F,2016-05-18,2016-06-08,6,JESUS DE NAZARETH,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
62467,7.397690e+13,5773334,F,2016-06-06,2016-06-08,65,SANTO ANTÔNIO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
32731,6.185450e+13,5773210,M,2016-06-06,2016-06-08,35,ITARARÉ,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
9851,7.622820e+11,5768595,F,2016-06-03,2016-06-08,9,DA PENHA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
9852,7.622820e+11,5768596,F,2016-06-03,2016-06-08,9,DA PENHA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
7313,2.599260e+11,5735287,F,2016-05-25,2016-06-08,6,DO QUADRO,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
9855,2.117990e+14,5778741,M,2016-06-06,2016-06-08,9,PRAIA DO SUÁ,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42166,3.394972e+08,5761778,F,2016-06-02,2016-06-08,45,SÃO JOSÉ,0,0,0,...,0,0,0,0,1,0,0,0,0,2016-06-07
32724,8.569150e+14,5757917,M,2016-06-01,2016-06-08,35,SANTA TEREZA,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
9856,1.598780e+14,5715870,M,2016-05-18,2016-06-08,9,PRAIA DO SUÁ,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
32721,8.189450e+13,5757721,M,2016-06-01,2016-06-08,35,ROMÃO,0,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
7312,2.599260e+11,5735288,F,2016-05-25,2016-06-08,6,DO QUADRO,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
42172,7.172450e+13,5575506,F,2016-04-13,2016-06-08,45,SANTA CECÍLIA,0,1,0,...,0,0,0,0,0,0,0,0,0,2016-06-07
48112,2.614560e+12,5698693,F,2016-05-16,2016-06-08,51,CARATOÍRA,1,0,0,...,0,0,0,0,0,0,0,0,0,2016-06-07

In [21]:
# הורדת שדות מיותרים
#df = df.drop(columns=['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay', 'No-show', 'Neighbourhood', 'Neighbourhood_codes','AppointmentDay'], axis = 1)

In [22]:
df.columns

Index([               'Age',        'Scholarship',       'Hipertension',
                 'Diabetes',         'Alcoholism',            'Handcap',
             'SMS_received',            'Gender_',           'No-show_',
              'Delta_Dates',             'Friday',             'Monday',
                 'Saturday',           'Thursday',            'Tuesday',
                'Wednesday', 'Appointment_counts',                    1,
                          2,                    3,                    4,
                          5,                    6,                    7,
                          8,                    9,                   10,
                         11,                   12,                   13,
                         14,                   15,                   16,
                         17,                   18,                   19,
                         20,                   21,                   22,
                         23,                   24,                   25,
                         26,                   27,                   28,
                         29,                   30,                   31,
                         32,                   33,                   34,
                         35,                   36,                   37,
                         38,                   39,                   40,
                         41,                   42,                   43,
                         44,                   45,                   46,
                         47,                   48,                   49,
                         50,                   51,                   53,
                         54,                   55,                   56,
                         57,                   58,                   59,
                         60,                   61,                   62,
                         63,                   64,                   65,
                         66,                   67,                   68,
                         69,                   70,                   71,
                         72,                   73,                   74,
                         75,                   76,                   77,
                         78,                   79,                   80,
                         81],
      dtype='object')

new_index_order = ['Age','Gender_','Delta_Dates','SMS_received', 'Friday', 'Monday', 'Saturday', 'Thursday', 'Tuesday', 'Wednesday','Scholarship', 'Hipertension', 'Diabetes', 'Alcoholism',
       'Handcap','No-show_']
df = df.reindex(columns=new_index_order)

In [24]:
df.head()

,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Gender_,No-show_,Delta_Dates,...,72,73,74,75,76,77,78,79,80,81
0,0,0,0,0,0,0,0,1,0,2,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,1,1,0,4,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,2,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,1,1,21,...,0,0,0,0,0,0,0,0,0,0

In [137]:
pickle.dump(df, open("df_c.dat", "wb"))